### ISSUE TITLE
Hightlight Stackables list resetting Ground Items list

### ISSUE THREAD

**Issue by Zelden848** [horse4lunch/highlight-stackable-items#4]
Having a list in the Highlight Stackables plugin will reset the list in Ground Items.

1. Enter a stackable in "highlight stackables" e.g. - coins
2. Go to Ground Items configand enter any items e.g. - iron bar
3. Close ground items config and reopen
4. Config will be reset to show "coins"

**Comment by horse4lunch** [comment]
So the text field in highlight stackables isn't for putting stackable items. You could just do that with with the normal ground items plugin. The plugin looks at your inventory and automatically adds anything that is stackable in your inventory to the ground items config list, Then removes it from the ground items config list when its no longer detected. So a good use for the plugin is when you are doing a slayer task or boss that drop noted items. I dont want single adamant bars to be highlighted all the time so i cant add it to my ground items config list, But if the mob im killing drops them noted i can pick up the drop then all further noted adamant bars will be highlighted until i deposit them, or get them out of my inventory. The side effect of this plugin though is that you can no longer directly make changes to the ground items config list. Thats what the list in highlight stackables is for. If you want whips to be highlighted all the time or iron bar in your example. Rather than putting it into the ground items config list you put it into highlight stackables config list. Anything in the highlight stackables config list will always be highlighted. This is mostly all explained in the readme on the front page. 

Il probably rework all this at some point. I actually already did, But there was an issue with how something was formatted when i tried uploading it to the plugin hub. I haven't really been playing runescape lately so its not been at the top of my priority list.
